apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: juice-shop-test
resources:
- juice-shop-ns.yaml
- juice-shop.yaml
- ingress.yaml
images:
- name: iurimihai/juice-shop
  newTag: test-0000000000000000000000000000000000000000
