apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: juice-shop-prod
resources:
- juice-shop-ns.yaml
- juice-shop.yaml
- ingress.yaml
images:
- name: iurimihai/juice-shop
  newTag: prod-0b84d764a009cde666ef9730b472c9c14b106d15
